### ISSUE TITLE
Namespacing the custom endpoints

### ISSUE THREAD

**Issue by yoren** [martin-pettersson/wp-rest-api-sidebars#1]
Hello Martin,

As the WP API v2 encourages us to namespace our custom endpoints (fyi: http://v2.wp-api.org/extending/adding/#namespacing), will you consider adopt this approach?

**Comment by martin-pettersson** [comment]
My initial thought was to use the core paths to push core development as I think these endpoints should be a part of core. But sure I will absolutely consider it.

**Comment by yoren** [comment]
Thanks for the fast response, good to know the reason you chose not to namespace it at this moment.

**Comment by martin-pettersson** [comment]
I decided to use a plugin specific namespace as you suggested: `wp-rest-api-sidebars/v1`.
The primary reason being I'm thinking about building a complete backend for widget administration. And as the current backend is slowly on the move (I've heard) it makes more sense and gives me more freedom to take it in my own direction.
