### ISSUE TITLE
WP_Autoloader and using wp-rest-api-sidebars within a theme

### ISSUE THREAD

**Issue by BenRacicot** [martin-pettersson/wp-rest-api-sidebars#2]
Hey Martin,

This plugin is seriously great work. I notice that the WP_Autoloader has no documentation so I wanted to ask a bit about it as well as how to use wp-rest-api-sidebars within a theme by itself. 

Is the autoloader specifically for loading WP plugins and what parts of wp-rest-api-sidebars are reliant on it? Thought I'd ask before I dig in, thanks for reading.

**Comment by martin-pettersson** [comment]
Hi, and thanks!
I will absolutely add documentation to the autoloader soon, but here's a quickie...

#### WP_Autoloader
The autoloader lets me get rid of include/require statements. It is based on the [PSR-4](http://www.php-fig.org/psr/psr-4) autoloader but follows [WordPress PHP Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/php/#naming-conventions).

In my plugin I tell the autoloader where to find my classes:
```php
<?php

// First I need to include the autoloader itself
require_once 'path/to/wp-autoloader.php';

// Create a new instance of the autoloader
$autoloader = new WP_Autoloader;

// Register the autoloader to the SPL autoloader stack
// This means that if a class cannot be found the autoloader will be asked to locate it
$autoloader->register();

// Tell it where to find my classes
// The classes with the top namespace "My_Plugin" can be
// found in the "path/to/classes" directory
$autoloader->add_namespace('My_Plugin', 'path/to/classes');

// The class "My_Plugin\Post_Iterator" cannot be found (because we haven't included the file)
// so the autoloader we have registered to the SPL autoloader stack will be asked to find it.
// The autoloader then converts "My_Plugin\Post_Iterator" to "path/to/classes/class-post-iterator.php"
// and includes the file. Inside the file there must be a class named Post_Iterator under the
// namespace "My_Plugin" or the class lookup will still fail.
$post_iterator = new My_Plugin\Post_Iterator;
```
In the plugin all classes inside the src directory will be autoloaded on demand. So when ever I need a class I just use it and the autoloader will include the file for me when I need it. All I have to do is follow the [WordPress PHP Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/php/#naming-conventions) when naming my files and classes and I'm good to go. You can take a look in the src directory of the plugin and see the file structure.

#### Using wp-rest-api-sidebars in a theme
All the plugin does is expose endpoints on the WP REST API. This allows you to render sidebars/widgets in a client based theme. For example if you are using angular-js on the front-end you can display a sidebar by fetching the url: `/wp-json/wp-rest-api-sidebars/v1/sidebars/{id}` and displaying the contents of the "rendered" field in the response. This is something that couldn't be done before and opens up some new possibilities.

I hope that I have answered your questions, if not just fire away and I will have another go at it!

**Comment by BenRacicot** [comment]
Hey Martin, What an amazing answer. Thanks so much. The autoloader looks great and your explanation is perfect. I think I've found some of the code you've used for the widgets at https://github.com/WP-API/wp-api-menus-widgets-endpoints is that the case? 

The reason I ask is because I'm building an Angular 2 front-end framework that replaces the WP core templating system. Therefore I need a bunch of well written endpoints. Do you think it's in my best interest to go straight to the source in order to build my sidebar/widget endpoint files or extract the code from your plugin?

**Comment by martin-pettersson** [comment]
No I wrote this plugin because there was no support for sidebars/widgets at the time. I was going to continue extending the plugin to expose endpoints for widget administration. But I read somewhere that there were going to be some big changes to how widgets were handled in core, so I decided not to and wait instead. Sadly I haven't had the interest to stay up to date with the progress, but it seems the WP-API have added end points for widgets now.

I would go directly for the WP-API source as this plugin only served as a way to get access to sidebars/widgets end points in a time where there were none.

**Comment by BenRacicot** [comment]
I see, it seems that the API team's code is extremely similar to yours. I watch the core track emails and it does seem like the API team has slowed/stopped abruptly. Maybe things are about to change as you've mentioned. Anyways, I appreciate your time and work. Thanks Martin!

**Comment by martin-pettersson** [comment]
I informed them of my plugin in an issue so perhaps they borrowed some of it! :-)

Yeah if all you need is the rendered widgets there should be enough functionality. But if you wish to add some administritative functionality it looks like you'll have to wait some more.

Thanks a bunch!
