### ISSUE TITLE
Support for v2

### ISSUE THREAD

**Issue by coolwebs** [martin-pettersson/wp-rest-api-sidebars#3]
Any plans to support WP 4.7 core or REST API V2?
I cannot get it to work. Really looking for a solution that will open up widgets on a WordPress CMS.

**Comment by martin-pettersson** [comment]
Hi! I'm sooo sorry for the response time on this one.
The plugin is developed for REST API V2 but I haven't tested it on newer versions. What kind of trouble are you experiencing?

**Comment by asaditsharma** [comment]
i use icy theme for last 4 years . In wordpress 4.7 sidebar not working .
developer of theme not able to contact.
please help me i don't want loose design.
