### ISSUE TITLE
i use icy theme for last 4 years . In wordpress 4.7 sidbar and layout not working? please help fast

### ISSUE THREAD

**Issue by asaditsharma** [martin-pettersson/wp-rest-api-sidebars#4]
i use icy theme for last 4 years . In wordpress 4.7 sidebar not working . please help fast?

**Comment by martin-pettersson** [comment]
In what way is it related to this plugin?

**Comment by asaditsharma** [comment]
these things related to WordPress 4.7

**Comment by martin-pettersson** [comment]
Are you using the WP REST API Sidebars plugin?
