### ISSUE TITLE
Is it dead?

### ISSUE THREAD

**Issue by ioandev** [martin-pettersson/wp-rest-api-sidebars#5]
`note: this plugin is under heavy development and will receive frequent feature updates (including documentation) so stay tuned`

**Comment by martin-pettersson** [comment]
Well...yes, it probably is.
I left it just the way it was since I have seen some people use it. But I really should update the status.

**Comment by ioandev** [comment]
What's your preferred way of getting the widgets from wordpress' widgets through the rest API?

**Comment by martin-pettersson** [comment]
I'm not really sure if there are other plugins that are more maintained providing similar functionality.
But I don't think this plugin is using any deprecated or unorthodox features. So it should be safe to use.
